# Generated by Django 4.1 on 2022-08-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watch_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='delivery',
        ),
    ]
